### ISSUE TITLE
Support for pattern matching on UriParameters

### ISSUE THREAD

**Issue by prisamuel** [go-raml/raml#3]
```
/albums:
    get:
        description: Retrieve a list of albums
    post:
            description: Create a new album
    /{isrc}:
        uriParameters: 
      isrc:
        description: The International Standard Recording Code which uniquely identifies this album
        type: string
        pattern: ^[a-zA-Z]{2}\-[0-9a-zA-Z]{3}\-\d{2}\-\d{5}$
        get:
            description: Retrieve the specified album
        put:
            description: Update an album        
        delete:
            description: Delete this album
```

The pattern field in the above raml example gets ignored when matching handlers to methods. When there are multiple handlers which support different types of UriParameters for the same resource, this is useful.
