### ISSUE TITLE
Cannot name a query parameter "type"

### ISSUE THREAD

**Issue by gennartan** [go-raml/raml#7]
It is not possible to name a query parameter "type" because it is wrongly interpreted by the parser.

Here is the error:
```
Failed parsing RAML file test.raml:
  Error parsing RAML:
  yaml: line 204: mapping values are not allowed in this context

```

The raml file looks like:
```
/myTest:
    get:
        description: Test
        queryParameters:
            param1:
                displayName: First parameter
                type: string
                example: hello
                required: true
            type:
                displayName: My type
                type: string
                required: false   
```
